#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Environment variables
export LC_ALL=en_US.UTF-8
#export http_proxy=

export MINECRAFT_MAGIC_LAUNCHER="~/Dropbox/Minecraft/MagicLauncher.jar"
export MINECRAFT_DEV_LAUNCHER="~/Dropbox/Minecraft/MinecraftDev.jar"
export MINECRAFT_LAUNCHER="~/Dropbox/Minecraft/minecraft.jar"
source "$HOME/.zsh_aliases"

# todo.txt settings
export TODOTXT_DATE_ON_ADD=1
export TODOTXT_DEFAULT_ACTION="ls"
alias t="todo.sh"
compdef t=todo.sh
