#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Environment variables
export LC_ALL=en_US.UTF-8
export HISTCONTROL=ignoreboth
#export http_proxy=

source "$HOME/.zsh_aliases"

# todo.txt settings
export TODOTXT_DATE_ON_ADD=1
export TODOTXT_DEFAULT_ACTION="ls"
alias t="todo.sh"
compdef t=todo.sh
